"""
Cache Manager
=============

Manages taxonomy profile caching for performance.

This is OPTIONAL - the system works without it. Cache is used
to avoid re-parsing taxonomies on every run.

CRITICAL: Cache files go to /taxonomies/.cache/, NEVER to /taxonomies/libraries/

Classes:
    CacheManager: Manages taxonomy profile cache
"""

from pathlib import Path
from typing import Optional
from datetime import datetime
import logging

from engines.fact_authority.taxonomy_reader.taxonomy_profile import TaxonomyProfile


logger = logging.getLogger(__name__)


class CacheManager:
    """
    Manages taxonomy profile cache.
    
    CRITICAL RULE: NEVER writes to /taxonomies/libraries/
    All cache files go to /taxonomies/.cache/
    
    Cache is OPTIONAL and can be disabled or deleted anytime.
    The taxonomy files in libraries/ remain the source of truth.
    """
    
    def __init__(self, cache_base_path: Path):
        """
        Initialize cache manager.
        
        Args:
            cache_base_path: Base cache directory (e.g., /taxonomies/.cache)
        """
        self.cache_base = cache_base_path
        self.profiles_dir = self.cache_base / 'profiles'
        
        # SAFETY CHECK: Ensure we're not in libraries/
        if 'libraries' in self.cache_base.parts:
            raise ValueError(
                f"FORBIDDEN: Cache path cannot be inside libraries/: {self.cache_base}"
            )
        
        # Ensure cache directory exists
        self._ensure_cache_directory()
    
    def _ensure_cache_directory(self):
        """
        Create cache directory structure if it doesn't exist.
        
        Handles permission issues by trying different approaches.
        """
        # Try standard creation
        try:
            self.cache_base.mkdir(parents=True, exist_ok=True)
            self.profiles_dir.mkdir(parents=True, exist_ok=True)
            
            # Verify it worked
            if not self.profiles_dir.exists():
                raise OSError(f"Directory creation appeared to succeed but directory not found: {self.profiles_dir}")
            
            # Create README explaining the cache
            readme = self.cache_base / 'README.txt'
            if not readme.exists():
                try:
                    readme.write_text(
                        "Taxonomy Profile Cache\n"
                        "======================\n\n"
                        "This directory contains cached taxonomy profiles generated by fact_authority.\n"
                        "These files are DERIVED from /taxonomies/libraries/ and can be safely deleted.\n"
                        "The system will regenerate them as needed.\n\n"
                        "DO NOT manually edit these files.\n"
                        "DO NOT commit these files to version control.\n\n"
                        f"Generated: {datetime.utcnow().isoformat()}\n"
                    )
                except Exception as e:
                    # README creation failed, but that's not critical
                    logger.debug(f"Could not create README: {e}")
            
            logger.info(f"Cache directory ready: {self.cache_base}")
            
        except PermissionError as e:
            logger.error(
                f"Permission denied creating cache directory: {self.cache_base}\n"
                f"  Error: {e}\n"
                f"  Solution: Run 'sudo mkdir -p {self.profiles_dir} && sudo chown -R $USER:$USER {self.cache_base}'"
            )
        except Exception as e:
            logger.error(
                f"Failed to create cache directory: {self.cache_base}\n"
                f"  Error: {e}\n"
                f"  Cache will be disabled for this session."
            )
    
    def get_cache_path(self, taxonomy_name: str, version: str) -> Path:
        """
        Get cache file path for a taxonomy.
        
        Args:
            taxonomy_name: Taxonomy name (e.g., 'us-gaap')
            version: Taxonomy version (e.g., '2025')
            
        Returns:
            Path to cache file
        """
        filename = f"{taxonomy_name}-{version}.profile.json"
        return self.profiles_dir / filename
    
    def is_cache_valid(
        self,
        cache_file: Path,
        source_taxonomy_path: Path
    ) -> bool:
        """
        Check if cached profile is still valid.
        
        Cache is invalid if:
        1. Cache file doesn't exist
        2. Source taxonomy has been modified since cache was created
        3. Cache format version is outdated
        
        Args:
            cache_file: Path to cached profile
            source_taxonomy_path: Path to source taxonomy in libraries/
            
        Returns:
            True if cache is valid and can be used
        """
        if not cache_file.exists():
            return False
        
        # Check modification time
        cache_mtime = cache_file.stat().st_mtime
        
        # Check if any schema file is newer than cache
        for schema_file in source_taxonomy_path.rglob('*.xsd'):
            if schema_file.stat().st_mtime > cache_mtime:
                logger.info(f"Cache invalid: {schema_file.name} modified")
                return False
        
        # Check catalog file
        catalog = source_taxonomy_path / 'catalog.xml'
        if catalog.exists() and catalog.stat().st_mtime > cache_mtime:
            logger.info("Cache invalid: catalog.xml modified")
            return False
        
        # Check format version
        try:
            profile = TaxonomyProfile.from_json(cache_file)
            if profile.format_version != '1.0':
                logger.info(f"Cache invalid: format version mismatch")
                return False
        except Exception as e:
            logger.warning(f"Cache invalid: cannot read {e}")
            return False
        
        return True
    
    def load_profile(self, cache_file: Path) -> Optional[TaxonomyProfile]:
        """
        Load cached profile.
        
        Args:
            cache_file: Path to cache file
            
        Returns:
            TaxonomyProfile or None if cannot load
        """
        if not cache_file.exists():
            return None
        
        try:
            profile = TaxonomyProfile.from_json(cache_file)
            logger.info(f"Loaded cached profile: {cache_file.name}")
            return profile
        except Exception as e:
            logger.warning(f"Failed to load cache: {e}")
            return None
    
    def save_profile(
        self,
        profile: TaxonomyProfile,
        cache_file: Path
    ):
        """
        Save profile to cache.
        
        SAFETY: This only writes to .cache/, never to libraries/
        
        Args:
            profile: Taxonomy profile to save
            cache_file: Path to cache file
            
        Raises:
            ValueError: If cache_file is in libraries/
        """
        # PARANOID SAFETY CHECK
        if 'libraries' in cache_file.parts:
            raise ValueError(
                f"FORBIDDEN: Attempted to write cache file inside libraries/: {cache_file}"
            )
        
        # Check if cache directory exists
        if not self.profiles_dir.exists():
            logger.warning(
                f"Cache directory does not exist: {self.profiles_dir}\n"
                f"  Attempting to create it now..."
            )
            try:
                self.profiles_dir.mkdir(parents=True, exist_ok=True)
                logger.info(f"Successfully created cache directory: {self.profiles_dir}")
            except Exception as e:
                logger.error(
                    f"Cannot create cache directory: {self.profiles_dir}\n"
                    f"  Error: {e}\n"
                    f"  Caching disabled. To enable:\n"
                    f"    sudo mkdir -p {self.profiles_dir}\n"
                    f"    sudo chown -R $USER:$USER {self.cache_base}"
                )
                return
        
        try:
            profile.to_json(cache_file)
            logger.info(f"Cached profile: {cache_file.name} ({cache_file.stat().st_size / 1024:.1f} KB)")
        except Exception as e:
            logger.error(f"Failed to save cache: {e}\n  File: {cache_file}")
    
    def clear_cache(self):
        """
        Delete all cached profiles.
        
        This is a safe operation - taxonomies in libraries/ are untouched.
        """
        import shutil
        
        if self.cache_base.exists():
            try:
                shutil.rmtree(self.cache_base)
                logger.info("Cache cleared")
                self._ensure_cache_directory()
            except Exception as e:
                logger.error(f"Failed to clear cache: {e}")
    
    def get_cache_info(self) -> dict:
        """
        Get information about cached profiles.
        
        Returns:
            Dictionary with cache statistics
        """
        if not self.profiles_dir.exists():
            return {
                'exists': False,
                'profile_count': 0,
                'total_size_mb': 0,
            }
        
        profile_files = list(self.profiles_dir.glob('*.json'))
        total_size = sum(f.stat().st_size for f in profile_files)
        
        return {
            'exists': True,
            'profile_count': len(profile_files),
            'total_size_mb': total_size / (1024 * 1024),
            'cache_path': str(self.cache_base),
            'profiles': [f.name for f in profile_files],
        }